# This is an action that is able to read a JSON file that contains the input to construct a test case.
# Input: JSON file
# Output: A list of environmental variables with new values. 

# The name of the action
name: Create directory structure for XDTesting

# Description of the action
description: This action is able to read a JSON file from the XDTesting app.

# Action icon and color
branding:
  icon: 'box'  
  color: 'blue'

runs:
  using: "composite"
  env:
    query: SELECT ?info ?name WHERE { ?person rdfs:seeAlso ?info . ?person foaf:homepage ?name .}
        
  # Steps that will be executed as part of the job
  steps:
    - name: Run SPARQL validator
      run: |
          function SPARQL_Reader () {
            reader_result="$( PYTHON_ARG="$1" python3 - <<END
          import json
 
          # Opening JSON file
          f = open('XDInput.json')
 
          # returns JSON object as a dictionary
          data = json.load(f)
 
          # Iterating through the json list
          for doc in data['fragments']:
            print(doc['name'], doc['ontologyName'])
            for item in doc['tests']:
              print(item['type'], item['content'], item['query'], item['id'])
 
          # Closing file
          f.close()
          END
          )"
            echo $validator_result
          }
          SPARQL_Validator "$query"
          
          
        
          
          
          
          
          
          
          
          
